# Generated by Django 2.2.6 on 2019-10-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oarex_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pay_terms', models.IntegerField(blank=True, null=True)),
                ('jurisdiction', models.CharField(max_length=30)),
                ('ownership', models.CharField(max_length=20)),
            ],
        ),
    ]
