# Generated by Django 2.2.6 on 2019-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oarex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtordata',
            name='company',
            field=models.CharField(default='dude', max_length=120),
            preserve_default=False,
        ),
    ]
