# Generated by Django 2.2.6 on 2019-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oarex', '0002_debtordata_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtordata',
            options={'ordering': ('company',)},
        ),
        migrations.AlterField(
            model_name='debtordata',
            name='company',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
